package vista;

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form farmacia
     */
    public Inicio() {
        initComponents();
        lblBusca.setVisible(false);
        jpnBusca.setVisible(false);
        txtCodBusca.setVisible(false);
        btnBuscar.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPrinci = new javax.swing.JLabel();
        jpnBusca = new javax.swing.JPanel();
        txtCodBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblBusca = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnIngreso = new javax.swing.JMenu();
        mnIIngresoP = new javax.swing.JMenuItem();
        mnILista = new javax.swing.JMenuItem();
        mnPersonal = new javax.swing.JMenu();
        mnIBusca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farmacia La Esquina");

        lblTituloPrinci.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloPrinci.setText("Examen-Contratación Personal");

        jpnBusca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscar.setText("Buscar");

        javax.swing.GroupLayout jpnBuscaLayout = new javax.swing.GroupLayout(jpnBusca);
        jpnBusca.setLayout(jpnBuscaLayout);
        jpnBuscaLayout.setHorizontalGroup(
            jpnBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBuscaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtCodBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jpnBuscaLayout.setVerticalGroup(
            jpnBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBusca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBusca.setText("Buscar producto por código");

        mnIngreso.setText("Ingreso Personal");

        mnIIngresoP.setText("Ingresar personal");
        mnIngreso.add(mnIIngresoP);

        mnILista.setText("Listar personal");
        mnILista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIListaActionPerformed(evt);
            }
        });
        mnIngreso.add(mnILista);

        jMenuBar1.add(mnIngreso);

        mnPersonal.setText("Personal");

        mnIBusca.setText("Busca persona");
        mnIBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIBuscaActionPerformed(evt);
            }
        });
        mnPersonal.add(mnIBusca);

        jMenuBar1.add(mnPersonal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblTituloPrinci))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jpnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblBusca)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTituloPrinci)
                .addGap(33, 33, 33)
                .addComponent(lblBusca)
                .addGap(18, 18, 18)
                .addComponent(jpnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnIListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnIListaActionPerformed

    private void mnIBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIBuscaActionPerformed
        lblBusca.setVisible(true);
        jpnBusca.setVisible(true);
        txtCodBusca.setVisible(true);
        btnBuscar.setVisible(true);
    }//GEN-LAST:event_mnIBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jpnBusca;
    public javax.swing.JLabel lblBusca;
    public javax.swing.JLabel lblTituloPrinci;
    public javax.swing.JMenuItem mnIBusca;
    public javax.swing.JMenuItem mnIIngresoP;
    public javax.swing.JMenuItem mnILista;
    public javax.swing.JMenu mnIngreso;
    public javax.swing.JMenu mnPersonal;
    public javax.swing.JTextField txtCodBusca;
    // End of variables declaration//GEN-END:variables

   
}
